# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm test
             
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_GM}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_GM}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL_GM}}
